Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
clicked
clicked
clicked
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
Traceback (most recent call last):
  File "E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py", line 21, in <module>
    tk.Spinbox(app, from_= 0, to=100, variable=sp).pack()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 4190, in __init__
    Widget.__init__(self, master, 'spinbox', cnf, kw)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: unknown option "-variable"
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
6
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
7

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 1
DS 0
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 
DS 
clicked
0
Python 0
DS 
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 3
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
Traceback (most recent call last):
  File "E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py", line 49, in <module>
    cmb_box = ttk.Combbox(app, textvariable=cmb, values=cmb_values)
AttributeError: module 'tkinter.ttk' has no attribute 'Combbox'
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 1
Combo: Project 4

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 1
Combo: Project 2
clicked
0
Python 0
DS 0
Batch: 1
Combo: Project 3
clicked
0
Python 0
DS 0
Batch: 1
Combo: Project 4

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 1
Combo: Project 2
clicked
0
Python 0
DS 0
Batch: 1
Combo: Project 4

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 1
Combo: 
DL
clicked
0
Python 0
DS 0
Batch: 1
Combo: Project 2
DL

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
Traceback (most recent call last):
  File "E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py", line 63, in <module>
    list_box = tk.Listbox(app, variable = lb)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 3162, in __init__
    Widget.__init__(self, master, 'listbox', cnf, kw)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: unknown option "-variable"
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
Traceback (most recent call last):
  File "E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py", line 63, in <module>
    list_box = tk.Listbox(app, textvariable = lb)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 3162, in __init__
    Widget.__init__(self, master, 'listbox', cnf, kw)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: unknown option "-textvariable"
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 1
Combo: 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py", line 27, in cmd
    print(list_box.get())
TypeError: get() missing 1 required positional argument: 'first'

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py", line 82, in opn
    file = tk.filedialog.askopenfile(mode='r',
AttributeError: module 'tkinter' has no attribute 'filedialog'

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
None
<_io.TextIOWrapper name='C:/Users/hp/Pictures/MATLAB icon.png' mode='r' encoding='cp1252'>
Traceback (most recent call last):
  File "E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py", line 90, in <module>
    app.mainloop()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
>>> file = tfd.askopenfile(mode='r',
                        filetypes = [('Images','*.png')])
>>> file.name
'C:/Users/hp/Pictures/MATLAB icon.png'
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
Traceback (most recent call last):
  File "E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py", line 94, in <module>
    can.create_image(20,20,anchor=tk.NW, image = img)
AttributeError: 'NoneType' object has no attribute 'create_image'
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
<_io.TextIOWrapper name='C:/Users/hp/Pictures/MATLAB icon.png' mode='r' encoding='cp1252'>
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
<_io.TextIOWrapper name='C:/Users/hp/Pictures/MATLAB icon.png' mode='r' encoding='cp1252'>
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
<_io.TextIOWrapper name='C:/Users/hp/Pictures/MATLAB icon.png' mode='r' encoding='cp1252'>
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
<_io.TextIOWrapper name='C:/Users/hp/Pictures/MATLAB icon.png' mode='r' encoding='cp1252'>
>>> 
===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
<_io.TextIOWrapper name='C:/Users/hp/Pictures/MATLAB icon.png' mode='r' encoding='cp1252'>
None

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 1
Combo: 

(1,)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py", line 36, in cmd
    print(list_box.get())
TypeError: get() missing 1 required positional argument: 'first'

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 1
Combo: 

(1,)
clicked
0
Python 0
DS 0
Batch: 1
Combo: 

(0,)
clicked
0
Python 0
DS 0
Batch: 1
Combo: 

(2,)

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 1
Combo: 

(1,)
Face Recognition

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
clicked
0
Python 0
DS 0
Batch: 1
Combo: 

(2,)
Speech Recognition

===== RESTART: E:/TN/SITP21/8thJune_B1_AI_ML/day12/script_file.py =====
[<_io.TextIOWrapper name='C:/Users/hp/Pictures/MATLAB icon.png' mode='r' encoding='cp1252'>, <_io.TextIOWrapper name='C:/Users/hp/Pictures/sanam peeyush.png' mode='r' encoding='cp1252'>, <_io.TextIOWrapper name='C:/Users/hp/Pictures/startmenu.png' mode='r' encoding='cp1252'>]

>>> 